[package]
name = "still"
version = "0.1.0"
authors = ["0xf00 <foo@anima.tech>"]
edition = "2018"

[build-dependencies.lalrpop]
version = "0.19.0"
features = ["lexer"]

[dependencies]
lalrpop-util = "0.19.3"
regex = "1"
rocket = "0.4.5"
rocket_contrib = "0.4.5"
serde = "1.0"
serde_json = "1.0"