name: Test

on:
  push:
    branches: [ master ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: select nightly
      run: rustup override set nightly
    - name: Run tests
      run: cargo test --verbose
